config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  get '/search', to: 'products#search', as: 'search'
  # get 'orders/index'
  # get 'orders/show'
  # get 'orders/new'
  # get 'orders/create'
  # get 'orders/update'

  resources :products do
    member do
      post 'favorite'
      delete 'unfavorite'
    end
  end

  resources :users do
    member do
      get 'show_favorites', as: 'show_favorites'
    end
  end

  resource :cart, only: [:show] do
    post 'add_to_cart/:product_id', action: :add_to_cart, on: :member, as: :add_to_cart
    delete 'remove_from_cart/:product_id', action: :remove_from_cart, on: :member, as: :remove_from_cart
  end

  # get '/users/show_favorites', to: 'users#show_favorites', as: :show_favorites

  resources :orders

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  delegate :price, to: :product, allow_nil: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :favorites
  has_many :favorited_products, through: :favorites, source: :product
  has_one :cart
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart
    @cart_items = @cart.cart_items
  end

  def add_to_cart
    @product = Product.find(params[:product_id])

    # Ensure the user has a cart, create one if not
    @cart = current_user.cart || current_user.create_cart

    # Check if the product is already in the cart
    unless @cart.products.include?(@product)
      @cart.products << @product
      flash[:notice] = 'Product added to cart!'
    else
      flash[:alert] = 'Product is already in the cart.'
    end

    redirect_to root_path
  end

  def remove_from_cart
    @product = Product.find(params[:product_id])
    @cart = current_user.cart

    if @cart && @cart.products.include?(@product)
      @cart.products.delete(@product)
      flash[:notice] = 'Product removed from cart!'
    else
      flash[:alert] = 'Product is not in the cart.'
    end

    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :favorite, :unfavorite]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by_id(params[:id])

    if @product
      @product
    else
      render file: "#{Rails.root}/public/404.html", layout: false
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save && product_params[:price].to_i >= 0
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { head :no_content }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find_by_id(params[:id])
  end

  def update
    @product = Product.find_by_id(params[:id])

    if @product.update(product_params) && product_params[:price].to_i >= 0
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      end
    else
      render file: "#{Rails.root}/public/422.html", layout: false
    end
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    if @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def favorite
    @product = Product.find(params[:id])
    current_user.favorited_products << @product unless current_user.favorited_products.include?(@product)
    # redirect_to show_favorites_user_path(current_user.id), notice: 'Product added to favorites.'
    redirect_to products_path, notice: 'Product added to favorites.'
  end

  def unfavorite
    @product = Product.find(params[:id])
    current_user.favorited_products.delete(@product)
    # redirect_to @product, notice: 'Product removed from favorites.'
    redirect_to products_path, notice: 'Product removed from favorites.'
  end

  def search
    @products = Product.where('name like ?', "%#{params[:query]}%")

    render :search
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :material, :quantity_available)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @countries = CountryService.get_countries
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show_favorites
    @user = User.find(params[:id])
    @favorite_products = @user.favorited_products
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :password, :password_confirmation, :name, :age, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/show.html.erb
<!-- app/views/carts/show.html.erb -->
<div class="container mt-4">
  <h1 class="display-4 mb-4 text-center">Your Shopping Cart</h1>

  <% if @cart_items.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Product</th>
          <th>Description</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.product.name %></td>
            <td><%= cart_item.product.description %></td>
            <td><%= number_to_currency(cart_item.product.price) %></td>
            <td>
              <%= link_to 'Remove from Cart', remove_from_cart_cart_path(cart_item.product), data: { turbo_method: :delete }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-end">
      <% total_price = @cart_items.sum { |cart_item| cart_item.product.price.to_f } %>
      <strong>Total:</strong> <%= number_to_currency(total_price) %>
    </div>
  <% else %>
    <div class="text-center">
      <p class="lead">Your cart is empty.</p>
    </div>
  <% end %>

  <%= link_to 'Continue Shopping', root_path, class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JewelleryStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
      function submitForm() {
       jQuery.ajax({
        url: '<%= search_path %>',
        type: 'GET',
        data: { query: $('#query').val() },
        success: function(data) {
          if(data)
          {
            console.log(data);
            $('#index').html(data);
          }
          
        }
      });
      };

    </script>
  </head>

  <body>
    <nav class="navbar navbar-light bg-dark">
      <div class="container-fluid">
        <a href="/"><%= image_tag("DGlogo.png", alt: "Logo Icon", class: "img-fluid logo-icon", style: "border-radius: 50%;height: 100px; width: auto;") %></a>
        <%# <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" onkeyup="searchFunction(value)">
        </form> %>
        <%= form_tag(search_path, method: :get, class: "d-flex") do %>
          <%= text_field_tag :query, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" }, onkeyup: "submitForm()" %>
        <% end %>
      </div>
    </nav>

    <% if user_signed_in? %>
      <p>Welcome : <%= current_user.name%></p>
      <p>Last login activity : <%= current_user.last_sign_in_at ? current_user.last_sign_in_at.strftime('%B %d, %Y %I:%M %p') : 'Never'%></p>
      <div class="d-flex justify-content-end">
        <%= button_to 'My Profile', user_path(current_user), method: :get, class: 'btn btn-info me2'%>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger me-2' %>
        <%= button_to "Show Favorites : #{current_user.favorites.count}", show_favorites_user_path(current_user.id), method: :get, class: 'btn btn-info' %>
        <%= link_to "Show Cart", cart_path%>
        <% cart_size = current_user.cart.cart_items.size %>
        <%= image_tag("shopping-cart-2.svg", alt: "Cart Icon", class: "img-fluid cart-icon #{'large' if cart_size > 10} #{'extra-large' if cart_size > 20}") %>
      </div>
    <% else %>
      <div class="d-flex justify-content-end">
        <%= button_to "Login", new_user_session_path, method: :get, class: 'btn btn-success me-2' %>
        <%= button_to "Signup", new_user_registration_path, method: :get, class: 'btn btn-secondary' %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/products/_form.html.erb
<!-- app/views/products/_form.html.erb -->

<%= form_with(model: product, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :quantity_available, class: 'form-label' %>
    <%= form.number_field :quantity_available, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :material, class: 'form-label' %>
    <%= form.text_field :material, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: 'form-label' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_result.html.erb
 <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @products.each do |product| %>
      <div class="col">
        <div class="card h-100">
          <% if product.image.present? %>
            <%= image_tag product.image, class: 'card-img-top', alt: 'Product Image' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text"><%= product.description %></p>
            <p class="card-text"><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
            <div>
              <%= link_to 'Details', product_path(product), class: 'btn btn-primary' %>
                <% if user_signed_in? %>
                  <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-secondary me-2' %>
                  <%= link_to 'Delete', product, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger', remote: true %>
                <% end %>
                <% if user_signed_in? && current_user.favorited_products.include?(product) %>
                  <%= link_to unfavorite_product_path(product), data: { turbo_method: :delete } do %>
                    <%= raw File.read(Rails.root.join('app/assets/images/heart.svg')) %>
                  <% end %>
                <% else %>
                  <%= link_to favorite_product_path(product), data: { turbo_method: :post } do %>
                    <%= raw File.read(Rails.root.join('app/assets/images/heart_blank.svg')) %>
                  <% end %>
                <% end %>
                <% if user_signed_in? && current_user.cart.products.include?(product)%>
                  <%= link_to "Remove from Cart", remove_from_cart_cart_path({product_id: product, user_id: current_user}), data: { turbo_method: :delete }, class: 'btn btn-danger'%>
                <%else%>
                  <%= link_to "Add to Cart", add_to_cart_cart_path({product_id: product, user_id: current_user}), data: { turbo_method: :post }, class: 'btn btn-info'%>
                <%end%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>


<!-- app/views/products/edit.html.erb -->

<div class="container mt-5">
  <h1 class="display-4">Edit Product</h1>
  <%= render 'form', product: @product %>
  <%= link_to 'Back to Products', products_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/products/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary mb-3' %>

<div class="container mt-4">
  <h1 class="display-4 mb-4 text-center">All Products</h1>
  <%= render 'result' %>
</div>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

<!-- app/views/products/new.html.erb -->

<div class="container mt-5">
  <h1 class="display-4">New Product</h1>
  <%= render 'form', product: @product %>
  <%= link_to 'Back to Products', products_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/products/search.html.erb
<% if @products.any?%>
<p>Search Results for: <%= params[:query] %></p>
  <%= render 'result'%>
<%else%>
  <p>No results found for the <%= params[:query]%></p>
<%end%>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<!-- app/views/products/show.html.erb -->

<div class="container mt-5">
  <h1 class="display-4"><%= @product.name %></h1>

  <div class="row">
    <div class="col-md-6">
      <% if @product.image.present?%>
        <%= image_tag @product.image, alt: 'Product Image', class: 'img-fluid mb-3' %>
      <%else%>
        <p>No Image Found</p>
      <%end%>
    </div>

    <div class="col-md-6">
      <p><strong>Description:</strong> <%= @product.description %></p>
      <p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
      <p><strong>Quantity Available:</strong> <%= @product.quantity_available %></p>
      <p><strong>Material:</strong> <%= @product.material %></p>

      <%= link_to 'Back to Products', products_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>


<!-- app/views/products/show.html.erb -->
<h1><%= @product.name %></h1>

<% if user_signed_in? %>
  <% if current_user.favorited_products.include?(@product) %>
    <%= button_to 'Remove from Favorites', unfavorite_product_path(@product), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Add to Favorites', favorite_product_path(@product), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->

<div class="user-profile">
  <h1>Edit Profile</h1>

  <%= form_for @user, html: { class: 'form' } do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.number_field :age, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'New Password' %>
      <%= f.password_field :password, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirm Password' %>
      <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, 'Profile Photo' %>
      <%= f.file_field :avatar, class: 'form-control-file' %>
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, class: 'avatar-preview' %>
      <% else %>
        <p>No profile photo available.</p>
      <% end %>
    </div>

     <div class="form-group">
      <%= f.label :country %>
      <%= f.select :country, @countries.map { |country| [country['name'], country['name']] }, { include_blank: 'Select Country' }, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back to Profile', user_path(@user), class: 'btn user_btn btn-secondary' %>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<div class="user-profile">
  <h1>User Profile</h1>

  <div class="profile-info">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, class: 'avatar' %>
    <% else %>
      <p>No profile photo available.</p>
    <% end %>

    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>Age:</strong> <%= @user.age %></p>
    <p><strong>Country:</strong> <%= @user.country %></p>
    <p><strong>Contact Details:</strong> <%= @user.email %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Created At:</strong> <%= @user.created_at.strftime('%B %d, %Y %I:%M %p') %></p>
    <p><strong>Last Sign In:</strong> <%= @user.last_sign_in_at ? @user.last_sign_in_at.strftime('%B %d, %Y %I:%M %p') : 'Never' %></p>
    <p><strong>Sign In Count:</strong> <%= @user.sign_in_count %></p>
    <!-- Add more fields as needed -->
  </div>

  <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn user_btn btn-primary' %>

</div>

app/views/users/show_favorites.html.erb
<!-- app/views/users/show_favorites.html.erb -->
<div class="container mt-4">
  <h1 class="display-4 mb-4 text-center"><%= @user.email %>'s Favorite Products</h1>

  <% if @favorite_products.any? %>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @favorite_products.each do |product| %>
        <div class="col">
          <div class="card h-100">
            <h5 class="card-title text-center"><%= product.name %></h5>

            <div class="card-body">
              <% if product.image.present? %>
                <%= image_tag product.image, alt: 'Product Image', class: 'card-img-top mb-3' %>
              <% else %>
                <p class="card-text text-muted">No Image Found</p>
              <% end %>

              <p class="card-text"><strong>Description:</strong> <%= product.description %></p>
              <p class="card-text"><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
              <p class="card-text"><strong>Quantity Available:</strong> <%= product.quantity_available %></p>
              <p class="card-text"><strong>Material:</strong> <%= product.material %></p>
            </div>

            <div class="card-footer text-center">
              <%= link_to unfavorite_product_path(product), data: { turbo_method: :delete } do %>
                <%= raw File.read(Rails.root.join('app/assets/images/heart.svg')) %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="text-center">
      <p class="lead">No favorite products yet.</p>
    </div>
  <% end %>
</div>